//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RubberDuckRent.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rented
    {
        public int id { get; set; }
        public Nullable<System.DateTime> rented_time { get; set; }
        public Nullable<System.DateTime> timest { get; set; }
        public Nullable<int> renter { get; set; }
        public Nullable<int> rented_from { get; set; }
        public Nullable<int> duck { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Ducks Ducks { get; set; }
        public virtual Renter Renter1 { get; set; }
    }
}
