//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RubberDuckRent.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RubberDuckRentEntities : DbContext
    {
        public RubberDuckRentEntities()
            : base("name=RubberDuckRentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Ducks> Ducks { get; set; }
        public virtual DbSet<Rented> Rented { get; set; }
        public virtual DbSet<Renter> Renter { get; set; }
    }
}
